terminal:
  container_name: qpep-terminal
  #image: pavja2/qpep:terminal
  build: terminal/
  ports:
    - "3141"
    - "5358"
    - "5926"
  volumes:
    - ../src/:/root/go/src
  environment:
    GOPATH: /root/go
  networks:
    gwlan:
      ipv4_address: 172.22.0.4
      priority: 900
    stlan:
      ipv4_address: 172.21.0.4
      priority: 1000
  privileged: true
  cap_add:
    - ALL
    - NET_ADMIN
  devices:
    - /dev/net/tun
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
ws-st:
  container_name: qpep-ws-st
  #image: pavja2/qpep:ws-st
  build: ws-st/
  networks:
    stlan:
      ipv4_address: 172.21.0.9
  privileged: true
  cap_add:
    - NET_ADMIN
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
  environment:
    DISPLAY:
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw