version: '2.4'
services:
  terminal:
    container_name: realworld-qpep-terminal
    build: terminal/
    ports:
      - "3141"
      - "5358"
      - "5926"
    networks:
      gwlan:
        ipv4_address: 172.22.0.4
    privileged: true
    cap_add:
      - ALL
      - NET_ADMIN
    devices:
      - /dev/net/tun
  ws-st:
    container_name: realworld-qpep-ws-st
    build: ws-st/
    networks:
      gwlan:
        ipv4_address: 172.22.0.9
    privileged: true
    cap_add:
      - NET_ADMIN
networks:
  gwlan:
    name: qpep-gwlan
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24