version: '2.4'
services:
  ws-gw:
    container_name: qpep-ws-gw
    #image: pavja2/qpep:ws-gw
    build: ws-gw/
    ports:
      - "0.0.0.0:4242:4242/udp"
      - "0.0.0.0:4242:4242/tcp"
      - "3141"
      - "5358"
      - "5926"
      - "0.0.0.0:5201:5201"
    networks:
      gwlan:
        ipv4_address: 172.22.0.9
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - "../../src/:/root/go/src"
    environment:
      GOPATH: /root/go
  tinyproxy:
    image: vimagick/tinyproxy
    ports:
      - "5001:8888"
    restart: always
    networks:
      gwlan:
        ipv4_address: 172.22.0.5
  ws-ovpn:
    container_name: ${WS_OVPN_CONTAINER_NAME:-ws-ovpn}
    #image: pavja2/qpep:ws-ovpn
    build: ws-ovpn/
    cap_add:
      - NET_ADMIN
    ports:
      - "0.0.0.0:${WS_OVPN_PORT:-1194}:1194/udp"
    volumes:
      - ./ws-ovpn/:/etc/openvpn
    sysctls:
      - net.ipv6.conf.all.disable_ipv6= 1
    networks:
      gwlan:
        ipv4_address: "${GW_NETWORK_HEAD:-172.22}.0.10"
networks:
  gwlan:
    name: qpep-gwlan
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
        - subnet: 2001:660:6602:142::1/64