version: '2.4'
services:
  ws-gw:
    container_name: qpep-ws-gw
    #image: pavja2/qpep:ws-gw
    build: ws-gw/
    ports:
      - "4242:4242"
    networks:
      gwlan:
        ipv4_address: 172.22.0.9
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - "../../src/:/root/go/src"
networks:
  gwlan:
    name: qpep-gwlan
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
        - subnet: 2001:660:6602:142::1/64